name: Python Auto Version Tag
description: Automatically generate new tags when version file changes
author: Sam Morgan
branding:
  icon: tag
  color: blue
inputs:
  path:
    description: Path to version file
    required: true
  variable:
    description: Variable name containing version information
    required: true
  prefix:
    description: Prefix to add to the version tag
    required: false
  suffix:
    description: Suffix to add to the version tag
    required: false
outputs:
  version:
    description: The version defined in the version file
runs:
  using: docker
  image: Dockerfile
